# Generated by Django 4.0.3 on 2022-04-17 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_professor'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('first_name', 'last_name')},
        ),
    ]
