# Generated by Django 4.0.3 on 2022-04-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_catalog_nume_elev'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='_privatename',
            field=models.CharField(default='mihai', max_length=50),
            preserve_default=False,
        ),
    ]
