# Generated by Django 4.0.3 on 2022-04-17 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_catalog__privatename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalog',
            old_name='_privatename',
            new_name='private_name',
        ),
    ]
