# Generated by Django 4.0.3 on 2022-04-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_rename__privatename_catalog_private_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='materie',
            field=models.CharField(choices=[('math', 'Math'), ('english', 'English'), ('science', 'Science')], default='biologie', max_length=50),
            preserve_default=False,
        ),
    ]
